version: 1.0
os: linux 
files:
  - source: /
    destination: /home/ubuntu/rcgenbackend
hooks:
  BeforeInstall:
    - location: scripts/codedeploy_before_install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/codedeploy_after_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/codedeploy_application_start.sh
      timeout: 300
      runas: ubuntu